% -------------------------------------------------------------------
%  Generated by MATLAB on 24-Nov-2020 13:17:06
%  MATLAB version: 9.9.0.1467703 (R2020b)
% -------------------------------------------------------------------
saveVarsMat = load('data_test.mat');

data_all = saveVarsMat.data_all; % <2000x2 double> too many elements

clear saveVarsMat;
